# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RVvyXyYFs5CYaJWrRBPMqL3mD-EgeJgQ
"""

n=int(input("Enter The Last Number: "))
a=0
b=1
c=0
print(a,end=" ")
while b<=n:
  print(b,end=" ")
  c=a+b
  a=b
  b=c